/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tankOyunu_Package;

import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author M-ORMAN09
 */

public class tankOyunu_JFrame extends javax.swing.JFrame {
static int x,y; 
int kalanZombieSayisi = 5;
public Icon winner_icon = new ImageIcon(getClass().getResource("/tankOyunuFoto_Package/winner_icon.png"));
    

    /**
     * Creates new form oyunDeneme_JFrame
     */
    public tankOyunu_JFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_sinirAlani = new javax.swing.JPanel();
        jPanel_oyunAlani = new javax.swing.JPanel();
        jLabel_tankAlani = new javax.swing.JLabel();
        jLabel_zombie = new javax.swing.JLabel();
        jTextField_kalanZombieSayisi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_sinirAlani.setBackground(new java.awt.Color(153, 102, 0));
        jPanel_sinirAlani.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel_oyunAlani.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_oyunAlani.setPreferredSize(new java.awt.Dimension(1900, 1060));

        jLabel_tankAlani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tankOyunuFoto_package/tank2_sag.png"))); // NOI18N

        jLabel_zombie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tankOyunuFoto_package/zombie.png"))); // NOI18N
        jLabel_zombie.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPanel_oyunAlaniLayout = new javax.swing.GroupLayout(jPanel_oyunAlani);
        jPanel_oyunAlani.setLayout(jPanel_oyunAlaniLayout);
        jPanel_oyunAlaniLayout.setHorizontalGroup(
            jPanel_oyunAlaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_oyunAlaniLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel_tankAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(401, 401, 401)
                .addComponent(jLabel_zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(542, Short.MAX_VALUE))
        );
        jPanel_oyunAlaniLayout.setVerticalGroup(
            jPanel_oyunAlaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_oyunAlaniLayout.createSequentialGroup()
                .addGroup(jPanel_oyunAlaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_oyunAlaniLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel_zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_oyunAlaniLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel_tankAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jTextField_kalanZombieSayisi.setBackground(new java.awt.Color(250, 250, 250));
        jTextField_kalanZombieSayisi.setFont(new java.awt.Font("Serif", 3, 32)); // NOI18N
        jTextField_kalanZombieSayisi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_kalanZombieSayisi.setText("KALAN ZOMBIE SAYISI : 5 ");
        jTextField_kalanZombieSayisi.setEnabled(false);

        javax.swing.GroupLayout jPanel_sinirAlaniLayout = new javax.swing.GroupLayout(jPanel_sinirAlani);
        jPanel_sinirAlani.setLayout(jPanel_sinirAlaniLayout);
        jPanel_sinirAlaniLayout.setHorizontalGroup(
            jPanel_sinirAlaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sinirAlaniLayout.createSequentialGroup()
                .addGroup(jPanel_sinirAlaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sinirAlaniLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel_oyunAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 1475, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_sinirAlaniLayout.createSequentialGroup()
                        .addGap(563, 563, 563)
                        .addComponent(jTextField_kalanZombieSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_sinirAlaniLayout.setVerticalGroup(
            jPanel_sinirAlaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sinirAlaniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_kalanZombieSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_oyunAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_sinirAlani, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        x = (int) jLabel_tankAlani.getBounds().getX();
        y = (int) jLabel_tankAlani.getBounds().getY();
     
        
        if(evt.getKeyCode()==KeyEvent.VK_D){
            
          Image icon1_Sag = new ImageIcon(this.getClass().getResource("/tankOyunuFoto_Package/tank1_sag.png")).getImage();
          jLabel_tankAlani.setIcon(new ImageIcon(icon1_Sag));  
          
          if(x<1347) x += 8;
          jLabel_tankAlani.setIcon(new ImageIcon(icon1_Sag));
          jLabel_tankAlani.setBounds(x, y, 128, 128);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_A){
         
          Image icon1_Sol = new ImageIcon(this.getClass().getResource("/tankOyunuFoto_Package/tank1_sol.png")).getImage();
          jLabel_tankAlani.setIcon(new ImageIcon(icon1_Sol));  
            
          if(x>0) x -= 8;
          jLabel_tankAlani.setIcon(new ImageIcon(icon1_Sol));
          jLabel_tankAlani.setBounds(x, y, 128, 128);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_W){
         
          Image icon1_Yukari = new ImageIcon(this.getClass().getResource("/tankOyunuFoto_Package/tank1_yukari.png")).getImage();
          jLabel_tankAlani.setIcon(new ImageIcon(icon1_Yukari));   
            
          if(y>0) y -= 8;
          jLabel_tankAlani.setIcon(new ImageIcon(icon1_Yukari));
          jLabel_tankAlani.setBounds(x, y, 128, 128);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_S){
         
          Image icon1_Asagi = new ImageIcon(this.getClass().getResource("/tankOyunuFoto_Package/tank1_asagi.png")).getImage();
          jLabel_tankAlani.setIcon(new ImageIcon(icon1_Asagi));  
            
          if(y<638) y += 8;
          jLabel_tankAlani.setIcon(new ImageIcon(icon1_Asagi));
          jLabel_tankAlani.setBounds(x, y, 128, 128);
        }
        
        Rectangle tankTipi = jLabel_tankAlani.getBounds();
        Rectangle zombieTipi = jLabel_zombie.getBounds();
        
    

       
    if(tankTipi.intersects(zombieTipi)){
          
           Random random = new Random();
           int maxX = jPanel_oyunAlani.getWidth()-jLabel_zombie.getWidth();
           int maxY = jPanel_oyunAlani.getHeight()-jLabel_zombie.getHeight();
           
           int randomX = random.nextInt(maxX);
           int randomy = random.nextInt(maxY);
           
           jLabel_zombie.setLocation(randomX, randomy);
           jPanel_oyunAlani.repaint();
           kalanZombieSayisi--;
       
              
        jTextField_kalanZombieSayisi.setText(String.valueOf("KALAN ZOMBIE SAYISI : "+kalanZombieSayisi));
        
        if (kalanZombieSayisi==0){
            
            JOptionPane.showMessageDialog(this, "", "GÖREV DURUMU", 1, winner_icon);
            this.setVisible(false); 
        }
         
         
      
        
      }

     
        
          
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tankOyunu_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tankOyunu_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tankOyunu_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tankOyunu_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tankOyunu_JFrame().setVisible(true);
        
      
               
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_tankAlani;
    private javax.swing.JLabel jLabel_zombie;
    private javax.swing.JPanel jPanel_oyunAlani;
    private javax.swing.JPanel jPanel_sinirAlani;
    private javax.swing.JTextField jTextField_kalanZombieSayisi;
    // End of variables declaration//GEN-END:variables
}
